import streamlit as st
import numpy as np
import pandas as pd
import joblib


st.set_page_config(
    page_title="Model page",
    page_icon="",
)
st.title("✈️Flight Dashboard")

model = joblib.load('logistic-reg-model.joblib')
# maybe we should adjust columns to what we have in our ml model, i.e. encoded features, but that will be over 800 column...
columns=["DepTime", "Airline", "Origin", "Dest", "DayOfWeek", "DayOfMonth", "Month"]

# Receive input
# Year = st.selectbox('Choose year', [2018, 2019, 2020, 2021, 2022])
Airline = st.selectbox('Choose airline', ['Southwest Airlines Co.', 'United Air Lines Inc.',
                                        'Delta Air Lines Inc.', 'Republic Airlines',
                                        'Hawaiian Airlines Inc.', 'American Airlines Inc.',
                                        'Allegiant Air', 'JetBlue Airways', 'SkyWest Airlines Inc.',
                                        'GoJet Airlines, LLC d/b/a United Express',
                                        'Frontier Airlines Inc.', 'ExpressJet Airlines Inc.',
                                        'Mesa Airlines Inc.', 'Capital Cargo International', 'Comair Inc.',
                                        'Alaska Airlines Inc.', 'Envoy Air', 'Air Wisconsin Airlines Corp',
                                        'Endeavor Air Inc.', 'Spirit Air Lines', 'Compass Airlines',
                                        'Horizon Air', 'Commutair Aka Champlain Enterprises, Inc.',
                                        'Trans States Airlines', 'Virgin America', 'Empire Airlines Inc.',
                                        'Cape Air', 'Peninsula Airways Inc.'])


airline_dict = {0: 'Hawaiian Airlines Inc.',
                1: 'GoJet Airlines, LLC d/b/a United Express',
                2: 'Southwest Airlines Co.',
                3: 'Republic Airlines',
                4: 'Comair Inc.',
                5: 'Spirit Air Lines',
                6: 'Cape Air',
                7: 'Frontier Airlines Inc.',
                8: 'Empire Airlines Inc.',
                9: 'ExpressJet Airlines Inc.',
                10: 'Capital Cargo International',
                11: 'Mesa Airlines Inc.',
                12: 'American Airlines Inc.',
                13: 'Horizon Air',
                14: 'SkyWest Airlines Inc.',
                15: 'Commutair Aka Champlain Enterprises, Inc.',
                16: 'Allegiant Air',
                17: 'Endeavor Air Inc.',
                18: 'Peninsula Airways Inc.',
                19: 'Delta Air Lines Inc.',
                20: 'JetBlue Airways',
                21: 'Air Wisconsin Airlines Corp',
                22: 'Compass Airlines',
                23: 'Virgin America',
                24: 'United Air Lines Inc.',
                25: 'Trans States Airlines',
                26: 'Alaska Airlines Inc.',
                27: 'Envoy Air'}

airport_dict = {0: 'ORD',
                1: 'HNL',
                2: 'ATL',
                3: 'YKM',
                4: 'PIE',
                5: 'ROP',
                6: 'RNO',
                7: 'HYS',
                8: 'TTN',
                9: 'LBF',
                10: 'HHH',
                11: 'CMH',
                12: 'MYR',
                13: 'SIT',
                14: 'BRD',
                15: 'BMI',
                16: 'CDC',
                17: 'SUN',
                18: 'ERI',
                19: 'ROW',
                20: 'OGD',
                21: 'IDA',
                22: 'VPS',
                23: 'GRI',
                24: 'RSW',
                25: 'PSM',
                26: 'SWF',
                27: 'JMS',
                28: 'LAS',
                29: 'PSG',
                30: 'MTJ',
                31: 'ORF',
                32: 'MSN',
                33: 'GUM',
                34: 'ONT',
                35: 'MHK',
                36: 'LGA',
                37: 'MEI',
                38: 'IAD',
                39: 'SBN',
                40: 'BET',
                41: 'SBA',
                42: 'OTZ',
                43: 'SAT',
                44: 'CLL',
                45: 'DUT',
                46: 'FAR',
                47: 'BQN',
                48: 'SMF',
                49: 'STC',
                50: 'GTR',
                51: 'ITO',
                52: 'HPN',
                53: 'BTM',
                54: 'SAF',
                55: 'YUM',
                56: 'CDV',
                57: 'GCK',
                58: 'HRL',
                59: 'ALO',
                60: 'EVV',
                61: 'FWA',
                62: 'DLH',
                63: 'STS',
                64: 'WRG',
                65: 'OAJ',
                66: 'CAE',
                67: 'HOB',
                68: 'TVC',
                69: 'BWI',
                70: 'GUC',
                71: 'MDW',
                72: 'PSE',
                73: 'PHF',
                74: 'FLO',
                75: 'FAT',
                76: 'CMX',
                77: 'TXK',
                78: 'LAW',
                79: 'LFT',
                80: 'ATW',
                81: 'EAU',
                82: 'EAT',
                83: 'PNS',
                84: 'LNK',
                85: 'ABR',
                86: 'CID',
                87: 'BLI',
                88: 'RFD',
                89: 'FSM',
                90: 'BPT',
                91: 'ACY',
                92: 'MKK',
                93: 'GSP',
                94: 'GEG',
                95: 'TYS',
                96: 'SCE',
                97: 'SPI',
                98: 'AEX',
                99: 'PUB',
                100: 'OMA',
                101: 'OTH',
                102: 'SDF',
                103: 'LWS',
                104: 'PIT',
                105: 'PVD',
                106: 'LCH',
                107: 'MLU',
                108: 'EYW',
                109: 'ISP',
                110: 'PQI',
                111: 'ATY',
                112: 'OGS',
                113: 'LEX',
                114: 'SFO',
                115: 'EKO',
                116: 'FLG',
                117: 'FCA',
                118: 'OAK',
                119: 'COU',
                120: 'STL',
                121: 'SJU',
                122: 'AVP',
                123: 'RDM',
                124: 'GNV',
                125: 'DAY',
                126: 'SJC',
                127: 'PBG',
                128: 'JST',
                129: 'CYS',
                130: 'ELP',
                131: 'LYH',
                132: 'BNA',
                133: 'AKN',
                134: 'PRC',
                135: 'MMH',
                136: 'HTS',
                137: 'USA',
                138: 'TBN',
                139: 'DDC',
                140: 'HIB',
                141: 'ACT',
                142: 'LAN',
                143: 'CGI',
                144: 'BLV',
                145: 'ECP',
                146: 'RIC',
                147: 'SLC',
                148: 'ILM',
                149: 'SRQ',
                150: 'PLN',
                151: 'BRW',
                152: 'LBL',
                153: 'MFE',
                154: 'SAV',
                155: 'GJT',
                156: 'CIU',
                157: 'HLN',
                158: 'DVL',
                159: 'BFF',
                160: 'PGD',
                161: 'MSO',
                162: 'AUS',
                163: 'CKB',
                164: 'DBQ',
                165: 'EAR',
                166: 'EWR',
                167: 'BTV',
                168: 'LRD',
                169: 'AVL',
                170: 'UIN',
                171: 'PDX',
                172: 'ANC',
                173: 'COD',
                174: 'PIA',
                175: 'RDD',
                176: 'AZO',
                177: 'FOD',
                178: 'BIL',
                179: 'ORH',
                180: 'LIH',
                181: 'GGG',
                182: 'LGB',
                183: 'LWB',
                184: 'JLN',
                185: 'LCK',
                186: 'DFW',
                187: 'CRW',
                188: 'RKS',
                189: 'TYR',
                190: 'ALW',
                191: 'ABI',
                192: 'MEM',
                193: 'SHD',
                194: 'ROC',
                195: 'GFK',
                196: 'MRY',
                197: 'BZN',
                198: 'DEN',
                199: 'JAN',
                200: 'BDL',
                201: 'CLE',
                202: 'AZA',
                203: 'ART',
                204: 'SAN',
                205: 'BFL',
                206: 'HSV',
                207: 'SCK',
                208: 'LNY',
                209: 'MSY',
                210: 'DSM',
                211: 'VLD',
                212: 'SNA',
                213: 'WYS',
                214: 'JAC',
                215: 'IMT',
                216: 'CAK',
                217: 'MKG',
                218: 'MIA',
                219: 'CRP',
                220: 'KTN',
                221: 'JHM',
                222: 'SJT',
                223: 'OKC',
                224: 'MLB',
                225: 'ESC',
                226: 'BKG',
                227: 'YAK',
                228: 'MBS',
                229: 'ACK',
                230: 'ABY',
                231: 'HOU',
                232: 'SYR',
                233: 'CMI',
                234: 'LAX',
                235: 'HGR',
                236: 'ASE',
                237: 'PSC',
                238: 'MOB',
                239: 'SGF',
                240: 'TWF',
                241: 'MSP',
                242: 'GTF',
                243: 'CVG',
                244: 'ROA',
                245: 'DCA',
                246: 'DHN',
                247: 'PIB',
                248: 'SLN',
                249: 'EWN',
                250: 'GSO',
                251: 'FLL',
                252: 'ABQ',
                253: 'JNU',
                254: 'FNT',
                255: 'ACV',
                256: 'PUW',
                257: 'STT',
                258: 'SWO',
                259: 'MKE',
                260: 'APN',
                261: 'BGM',
                262: 'XWA',
                263: 'OME',
                264: 'VEL',
                265: 'RDU',
                266: 'IPT',
                267: 'CNY',
                268: 'SFB',
                269: 'GST',
                270: 'BUF',
                271: 'BGR',
                272: 'DLG',
                273: 'PSP',
                274: 'FAI',
                275: 'CPR',
                276: 'ADQ',
                277: 'BOS',
                278: 'SBY',
                279: 'TRI',
                280: 'COS',
                281: 'IAH',
                282: 'GRK',
                283: 'VCT',
                284: 'FSD',
                285: 'PAE',
                286: 'RAP',
                287: 'BTR',
                288: 'ITH',
                289: 'PHX',
                290: 'PWM',
                291: 'MAF',
                292: 'BOI',
                293: 'JAX',
                294: 'ELM',
                295: 'SPN',
                296: 'MCI',
                297: 'IAG',
                298: 'BUR',
                299: 'AMA',
                300: 'DIK',
                301: 'STX',
                302: 'MFR',
                303: 'HYA',
                304: 'DTW',
                305: 'SEA',
                306: 'DRO',
                307: 'LIT',
                308: 'CHO',
                309: 'DRT',
                310: 'MCW',
                311: 'SUX',
                312: 'CSG',
                313: 'PBI',
                314: 'MGM',
                315: 'CHS',
                316: 'MOT',
                317: 'SGU',
                318: 'GCC',
                319: 'HDN',
                320: 'OGG',
                321: 'DAB',
                322: 'MVY',
                323: 'TUL',
                324: 'SBP',
                325: 'EUG',
                326: 'BHM',
                327: 'KOA',
                328: 'MLI',
                329: 'MDT',
                330: 'CLT',
                331: 'IND',
                332: 'JFK',
                333: 'GPT',
                334: 'LAR',
                335: 'BIS',
                336: 'GRB',
                337: 'AGS',
                338: 'PAH',
                339: 'RIW',
                340: 'SHV',
                341: 'XNA',
                342: 'LBE',
                343: 'TUS',
                344: 'TLH',
                345: 'ABE',
                346: 'PGV',
                347: 'ALS',
                348: 'ICT',
                349: 'CWA',
                350: 'GRR',
                351: 'INL',
                352: 'MQT',
                353: 'CHA',
                354: 'HVN',
                355: 'MHT',
                356: 'ALB',
                357: 'FAY',
                358: 'RST',
                359: 'SHR',
                360: 'BRO',
                361: 'TOL',
                362: 'PHL',
                363: 'BIH',
                364: 'PIH',
                365: 'PVU',
                366: 'RHI',
                367: 'LSE',
                368: 'LBB',
                369: 'SPS',
                370: 'TPA',
                371: 'EGE',
                372: 'BJI',
                373: 'SCC',
                374: 'PIR',
                375: 'MCO',
                376: 'PPG',
                377: 'DAL',
                378: 'BQK',
                379: 'ISN'}


origin_list = ['SAN', 'DEN', 'MCO', 'ATL', 'ORD', 'LIH', 'BOS', 'IAD', 'DTW',
            'ELM', 'HPN', 'PHX', 'BUF', 'DFW', 'PAH', 'TUS', 'LAS', 'ICT',
            'IND', 'IAH', 'BTV', 'CLT', 'ORF', 'PDX', 'EYW', 'RNO', 'MEM',
            'SFO', 'CLE', 'PSG', 'ITO', 'PWM', 'MDT', 'MYR', 'TYS', 'MSP',
            'PHL', 'SRQ', 'SEA', 'TPA', 'SNA', 'BNA', 'OAK', 'RIC', 'EVV',
            'ACY', 'MFE', 'MIA', 'SLC', 'DCA', 'RDU', 'SWO', 'JAX', 'EWR',
            'LAX', 'FWA', 'JFK', 'OKC', 'HOU', 'BOI', 'SBP', 'SYR', 'KOA',
            'ELP', 'TUL', 'LWB', 'BWI', 'MRY', 'DSM', 'LGA', 'SMF', 'ONT',
            'STS', 'SDF', 'ROA', 'LIT', 'SJU', 'AGS', 'SJC', 'FLL', 'ABQ',
            'HNL', 'CMH', 'ALB', 'PIT', 'LGB', 'RSW', 'PNS', 'SBA', 'CVG',
            'PIA', 'MKE', 'KTN', 'FSM', 'PBI', 'STL', 'MCI', 'MSN', 'BDL',
            'MDW', 'CHA', 'AUS', 'TVC', 'MLU', 'ROC', 'SAV', 'BHM', 'DAL',
            'HHH', 'BUR', 'INL', 'MGM', 'CHS', 'RDM', 'GEG', 'GSP', 'MHT',
            'ABE', 'PSP', 'FAR', 'ILM', 'FNT', 'MLI', 'ATW', 'AZA', 'TYR',
            'JST', 'MAF', 'MSY', 'HSV', 'TRI', 'SAF', 'ASE', 'ANC', 'AMA',
            'JAN', 'ABI', 'PVD', 'BZN', 'PHF', 'MSO', 'CHO', 'COS', 'UIN',
            'SJT', 'PSC', 'OGG', 'LBB', 'BGR', 'SAT', 'OMA', 'SGU', 'AVP',
            'XNA', 'MVY', 'CID', 'BQK', 'ATY', 'MHK', 'DIK', 'LRD', 'DAY',
            'RAP', 'BRO', 'MOB', 'GRR', 'FSD', 'GRI', 'AZO', 'JNU', 'IDA',
            'FAT', 'CSG', 'CMX', 'CRP', 'BMI', 'SFB', 'HRL', 'GSO', 'PLN',
            'LSE', 'VPS', 'LAW', 'SGF', 'AKN', 'LFT', 'PIB', 'STT', 'GRB',
            'ECP', 'LCK', 'STX', 'LWS', 'LNK', 'SLN', 'BLI', 'BFL', 'ERI',
            'JAC', 'LEX', 'SBN', 'BTR', 'HDN', 'LAR', 'CPR', 'FAY', 'BRD',
            'BIH', 'LYH', 'DRO', 'EKO', 'SBY', 'CWA', 'ISP', 'YKM', 'CDV',
            'EUG', 'JLN', 'TLH', 'CMI', 'DHN', 'MFR', 'ACK', 'EAU', 'FCA',
            'PSM', 'RDD', 'EGE', 'GJT', 'ACV', 'CAE', 'CRW', 'GUM', 'PPG',
            'PGD', 'PUB', 'PAE', 'AEX', 'YAK', 'AVL', 'GUC', 'SHV', 'BIS',
            'CDB', 'MTJ', 'SHR', 'PIE', 'ACT', 'HOB', 'COD', 'ALW', 'BLV',
            'DAB', 'TOL', 'DBQ', 'GTF', 'SUN', 'ART', 'BPT', 'WRG', 'CKB',
            'HGR', 'FAI', 'GFK', 'SWF', 'BJI', 'GRK', 'CDC', 'MQT', 'ISN',
            'YUM', 'LAN', 'DLH', 'IAG', 'DVL', 'ABR', 'MKK', 'CAK', 'BIL',
            'CIU', 'JHM', 'GPT', 'RST', 'APN', 'MEI', 'PGV', 'CLL', 'MLB',
            'TXK', 'HVN', 'GNV', 'VLD', 'PBG', 'XWA', 'OWB', 'COU', 'OGS',
            'FLG', 'SCE', 'SUX', 'MOT', 'SIT', 'OTZ', 'ITH', 'PVU', 'OAJ',
            'LBE', 'ROW', 'TWF', 'SHD', 'DDC', 'RKS', 'BFF', 'GCK', 'EWN',
            'SPI', 'HLN', 'LNY', 'JMS', 'IMT', 'ORH', 'USA', 'FLO', 'PIH',
            'EAT', 'ADQ', 'SPN', 'LBF', 'SPS', 'GTR', 'DEC', 'DRT', 'HTS',
            'CYS', 'MCW', 'CGI', 'BTM', 'BRW', 'PRC', 'LCH', 'SCK', 'TTN',
            'BQN', 'CNY', 'PSE', 'EAR', 'HIB', 'BGM', 'GCC', 'MKG', 'MBS',
            'SCC', 'VEL', 'LBL', 'GGG', 'WYS', 'ABY', 'HYS', 'ALO', 'BET',
            'OTH', 'RFD', 'RHI', 'DLG', 'PIR', 'RIW', 'VCT', 'PQI', 'PUW',
            'IPT', 'MMH', 'SMX', 'ADK', 'BKG', 'FOD', 'DUT', 'TBN', 'ALS',
            'ESC', 'BFM', 'ROP', 'OME', 'HYA']

dest_list = ['PDX', 'IAH', 'DAL', 'IND', 'PWM', 'OGG', 'DCA', 'RSW', 'MSP',
            'SAT', 'SFB', 'MCO', 'CLT', 'DEN', 'MCI', 'PNS', 'GRR', 'FCA',
            'ORD', 'RIC', 'DFW', 'JFK', 'GEG', 'EWR', 'DTW', 'PHL', 'LGA',
            'ATL', 'CAE', 'LAS', 'MIA', 'HOU', 'STT', 'PHX', 'SFO', 'SNA',
            'JNU', 'LEX', 'HNL', 'IAD', 'MSN', 'BMI', 'AUS', 'BDL', 'SMF',
            'BOI', 'XNA', 'BTR', 'PIT', 'MYR', 'COS', 'BWI', 'LAX', 'GSP',
            'DAY', 'FLL', 'BNA', 'CWA', 'ABE', 'OAJ', 'MFE', 'AEX', 'SAV',
            'CLE', 'RDU', 'SEA', 'SAN', 'STL', 'MDT', 'FAT', 'ORF', 'OMA',
            'LWS', 'RDM', 'LYH', 'BOS', 'BUR', 'GJT', 'CVG', 'SLC', 'ANC',
            'BHM', 'MDW', 'FWA', 'FSD', 'PGD', 'TUS', 'JAX', 'MSY', 'OAK',
            'ITO', 'MHK', 'AGS', 'GRB', 'MHT', 'MAF', 'DSM', 'BRO', 'BUF',
            'CMH', 'PVD', 'ASE', 'SJC', 'ERI', 'PRC', 'CHA', 'SJU', 'JAC',
            'PBI', 'HLN', 'JLN', 'EUG', 'HPN', 'TUL', 'ONT', 'LBB', 'RDD',
            'LIT', 'CID', 'ROA', 'ITH', 'DAB', 'MKE', 'ILM', 'TPA', 'DLH',
            'GSO', 'SHD', 'MFR', 'IDA', 'LFT', 'MLU', 'CHS', 'MGM', 'GCC',
            'OKC', 'GRK', 'ABQ', 'MRY', 'EVV', 'SDF', 'AMA', 'RNO', 'BTV',
            'LAW', 'LAN', 'YUM', 'MSO', 'STS', 'BZN', 'BPT', 'KOA', 'ISN',
            'SRQ', 'MEM', 'CAK', 'EYW', 'AVL', 'TWF', 'LGB', 'LIH', 'ALB',
            'BQN', 'MLI', 'TLH', 'BFL', 'ACT', 'ISP', 'AZO', 'ALO', 'MOB',
            'GFK', 'SGF', 'MBS', 'SPI', 'AVP', 'LRD', 'ELP', 'DDC', 'PIE',
            'ROW', 'PHF', 'LSE', 'TYS', 'SHV', 'MOT', 'LNK', 'SYR', 'PSC',
            'SAF', 'FOD', 'TVC', 'MEI', 'AZA', 'HRL', 'FSM', 'HSV', 'VPS',
            'KTN', 'ACY', 'JAN', 'HDN', 'ESC', 'HYS', 'DRO', 'GTF', 'FNT',
            'PAH', 'TRI', 'ECP', 'BGR', 'GPT', 'SBN', 'FAR', 'ATW', 'FAY',
            'CHO', 'HTS', 'LBE', 'CDC', 'ELM', 'HIB', 'MTJ', 'COD', 'JMS',
            'ROC', 'RST', 'TTN', 'BIS', 'GNV', 'LWB', 'MLB', 'SBA', 'HHH',
            'PSP', 'BIL', 'SGU', 'EWN', 'PSG', 'SCE', 'RAP', 'STX', 'SCC',
            'ATY', 'CDV', 'BLV', 'ALS', 'ICT', 'SBY', 'TXK', 'PQI', 'RFD',
            'IPT', 'GTR', 'EGE', 'FAI', 'ADQ', 'EAR', 'CMI', 'SCK', 'PAE',
            'CRW', 'OTH', 'CRP', 'LCH', 'SBP', 'BLI', 'CPR', 'FLG', 'CLL',
            'SIT', 'CSG', 'USA', 'ABY', 'PPG', 'SPS', 'PIA', 'TYR', 'COU',
            'IMT', 'ART', 'EAT', 'CMX', 'PUB', 'CNY', 'PSE', 'MMH', 'ACV',
            'MKK', 'ACK', 'VCT', 'PUW', 'GGG', 'BTM', 'SJT', 'DBQ', 'BET',
            'ABI', 'GCK', 'BJI', 'PIR', 'ORH', 'PVU', 'OME', 'PSM', 'TOL',
            'XWA', 'STC', 'PIB', 'MVY', 'BQK', 'SWF', 'DRT', 'CKB', 'LBL',
            'YKM', 'LNY', 'WYS', 'BRW', 'GUM', 'SUN', 'RKS', 'ADK', 'MQT',
            'JHM', 'OGS', 'BFF', 'IAG', 'PIH', 'SHR', 'FLO', 'GRI', 'SPN',
            'YAK', 'EAU', 'MKG', 'ALW', 'OTZ', 'LAR', 'SUX', 'BRD', 'DIK',
            'UIN', 'CIU', 'BGM', 'LCK', 'PGV', 'DHN', 'DUT', 'CGI', 'HVN',
            'RHI', 'EKO', 'PLN', 'BKG', 'GUC', 'PBG', 'SLN', 'OWB', 'SMX',
            'RIW', 'LBF', 'VEL', 'ABR', 'WRG', 'DVL', 'CDB', 'HGR', 'VLD',
            'APN', 'DEC', 'DLG', 'INL', 'CYS', 'BIH', 'SWO', 'AKN', 'HOB',
            'HYA', 'OGD', 'JST', 'TBN']



Origin = st.selectbox('Choose origin',sorted(origin_list))
Dest = st.selectbox('Choose destination',sorted(dest_list) )
#Cancelled = st.selectbox('Is flight cancelled', [0, 1])
DepTime = st.slider('Depature Time', 1, 2400)
# DepDelayMinutes = st.slider('Depature delay minutes', 0, 1653)

#DepDel15 = st.selectbox('Is flight delayed for more than 15 minutes', [0, 1])
# DepTimeBlk = st.selectbox('Choose departure time block', ['1900-1959', '0001-0559', '2100-2159', '1500-1559', '1200-1259',
#        '1100-1159', '1700-1759', '0700-0759', '1400-1459', '1300-1359',
#        '1000-1059', '2200-2259', '0600-0659', '2300-2359', '0800-0859',
#        '0900-0959', '1800-1859', '2000-2059', '1600-1659'])

Month = st.selectbox('Choose Month', [1, 2, 3, 4, 5, 6, 7,8,9,10,11,12])
day_month = [8, 21, 20,  3,  9, 17, 14, 23,  2,  6, 10, 30,  5, 26, 13, 15, 16, 7, 11,  1, 27, 22, 19, 12, 31,  4, 29, 24, 28, 18, 25]
DayOfMonth = st.selectbox('Choose day of month', sorted(day_month))
DayOfWeek = st.selectbox('Choose day of week', [1, 2, 3, 4, 5, 6, 7])


Airline = [k for k, v in airline_dict.items() if v == Airline][0]
Origin = [k for k, v in airport_dict.items() if v == Origin][0]
Dest = [k for k, v in airport_dict.items() if v == Dest][0]

def predict():

    airline_dict = {0: 'Hawaiian Airlines Inc.',
                1: 'GoJet Airlines, LLC d/b/a United Express',
                2: 'Southwest Airlines Co.',
                3: 'Republic Airlines',
                4: 'Comair Inc.',
                5: 'Spirit Air Lines',
                6: 'Cape Air',
                7: 'Frontier Airlines Inc.',
                8: 'Empire Airlines Inc.',
                9: 'ExpressJet Airlines Inc.',
                10: 'Capital Cargo International',
                11: 'Mesa Airlines Inc.',
                12: 'American Airlines Inc.',
                13: 'Horizon Air',
                14: 'SkyWest Airlines Inc.',
                15: 'Commutair Aka Champlain Enterprises, Inc.',
                16: 'Allegiant Air',
                17: 'Endeavor Air Inc.',
                18: 'Peninsula Airways Inc.',
                19: 'Delta Air Lines Inc.',
                20: 'JetBlue Airways',
                21: 'Air Wisconsin Airlines Corp',
                22: 'Compass Airlines',
                23: 'Virgin America',
                24: 'United Air Lines Inc.',
                25: 'Trans States Airlines',
                26: 'Alaska Airlines Inc.',
                27: 'Envoy Air'}


    row=np.array([DepTime, Airline, Origin, Dest, Month,  DayOfWeek, DayOfMonth])
    X = pd.DataFrame([row], columns=columns)
    prediction = model.predict(X)[0]
    st.header(airline_dict[Airline])


    if prediction == 0:
        st.success('Flight will be on time :thumbsup:')
    elif prediction ==1:
        st.warning('Flight will be slightly delayed within 15 minutes')
    elif prediction ==2:
        st.warning('Flight will be delayed within 30 minutes')
    elif prediction ==3:
        st.error('Flight will be hugly delayed within 60 minutes, icon="⚠️"')
    else:
        st.error('Flight will be delayed a lot. Recommend to choose different Airline, icon="🚨"')

    st.markdown("""---""")

    st.header("Recommend Different Airline")

    for key, value in airline_dict.items():
        recommedn_Airline = key 
        row=np.array([DepTime, recommedn_Airline, Origin, Dest, Month,  DayOfWeek, DayOfMonth])
        X = pd.DataFrame([row], columns=columns)
        prediction1 = model.predict(X)[0]

        if prediction1 < prediction:
            if prediction1 == 0:
                st.subheader(airline_dict[key])
                st.success('This flight will be on time :thumbsup:')
            elif prediction1 ==1:
                st.subheader(airline_dict[key])
                st.warning('This flight will be slightly delayed within 15 minutes')
            elif prediction1 ==2:
                st.subheader(airline_dict[key])
                st.warning('This flight will be delayed within 30 minutes')
                

st.button('Predict', on_click=predict)